// <auto-generated />
using System;
using AspnetCoreMvcFull.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspnetCoreMvcFull.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501064931_RefactoredShift1")]
    partial class RefactoredShift1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtByPIC")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByPIC")
                        .HasColumnType("text");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CancelledBy")
                        .HasColumnType("integer");

                    b.Property<string>("CancelledByName")
                        .HasColumnType("text");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("text");

                    b.Property<string>("CostCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CraneId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomHazard")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DoneByPIC")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ManagerApprovalTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("ManagerRejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PICRejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProjectSupervisor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CraneId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingHazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("HazardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("HazardId");

                    b.ToTable("BookingHazards");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShiftDefinitionId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ShiftEndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ShiftDefinitionId");

                    b.ToTable("BookingShifts");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Breakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualUrgentEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CraneId")
                        .HasColumnType("integer");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UrgentEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UrgentStartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CraneId");

                    b.ToTable("Breakdowns");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Crane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cranes");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Hazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Hazards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Listrik Tegangan Tinggi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kondisi Tanah"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bekerja di Dekat Bangunan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bekerja di Dekat Area Mining"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bekerja di Dekat Air"
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.MaintenanceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CraneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CraneId");

                    b.ToTable("MaintenanceSchedules");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.MaintenanceScheduleShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaintenanceScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftDefinitionId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ShiftEndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceScheduleId");

                    b.HasIndex("ShiftDefinitionId");

                    b.ToTable("MaintenanceScheduleShifts");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Role.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LdapUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LdapUser", "RoleName")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            LdapUser = "PIC1",
                            Notes = "Default admin user created by seeder",
                            RoleName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system",
                            LdapUser = "PIC1",
                            Notes = "Default admin user created by seeder",
                            RoleName = "pic"
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ShiftDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("ShiftDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            IsActive = true,
                            Name = "Morning Shift",
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 23, 0, 0, 0),
                            IsActive = true,
                            Name = "Evening Shift",
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 7, 0, 0, 0),
                            IsActive = true,
                            Name = "Night Shift",
                            StartTime = new TimeSpan(0, 23, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            IsActive = true,
                            Name = "First Half Day",
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            Name = "Second Half Day",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Booking", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Crane", "Crane")
                        .WithMany()
                        .HasForeignKey("CraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crane");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingHazard", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Booking", "Booking")
                        .WithMany("BookingHazards")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.Hazard", "Hazard")
                        .WithMany()
                        .HasForeignKey("HazardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Hazard");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingItem", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.BookingShift", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Booking", "Booking")
                        .WithMany("BookingShifts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.ShiftDefinition", "ShiftDefinition")
                        .WithMany("BookingShifts")
                        .HasForeignKey("ShiftDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ShiftDefinition");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Breakdown", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Crane", "Crane")
                        .WithMany("Breakdowns")
                        .HasForeignKey("CraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crane");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.Crane", "Crane")
                        .WithMany()
                        .HasForeignKey("CraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crane");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.MaintenanceScheduleShift", b =>
                {
                    b.HasOne("AspnetCoreMvcFull.Models.MaintenanceSchedule", "MaintenanceSchedule")
                        .WithMany("MaintenanceScheduleShifts")
                        .HasForeignKey("MaintenanceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspnetCoreMvcFull.Models.ShiftDefinition", "ShiftDefinition")
                        .WithMany()
                        .HasForeignKey("ShiftDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceSchedule");

                    b.Navigation("ShiftDefinition");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Booking", b =>
                {
                    b.Navigation("BookingHazards");

                    b.Navigation("BookingItems");

                    b.Navigation("BookingShifts");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.Crane", b =>
                {
                    b.Navigation("Breakdowns");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.MaintenanceSchedule", b =>
                {
                    b.Navigation("MaintenanceScheduleShifts");
                });

            modelBuilder.Entity("AspnetCoreMvcFull.Models.ShiftDefinition", b =>
                {
                    b.Navigation("BookingShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
